spring.application.name=mindarena-api-gateway
server.port=${PORT:8080}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=mindarena-web
spring.cloud.gateway.routes[0].uri=lb://mindarena-app
spring.cloud.gateway.routes[0].predicates[0]=Path=/**

management.endpoints.web.exposure.include=health,info,gateway
