apiVersion: v1
kind: ConfigMap
metadata:
  name: mindarena-config
  namespace: mindarena
data:
  eureka-default-zone: http://discovery:8761/eureka/
  redis-host: redis
  redis-port: "6379"
  rabbitmq-host: rabbitmq
  rabbitmq-port: "5672"
