apiVersion: v1
kind: Secret
metadata:
  name: mindarena-secrets
  namespace: mindarena
type: Opaque
stringData:
  db-username: replace-with-db-user
  db-password: replace-with-db-password
  db-root-password: replace-with-db-root-password
  rabbitmq-username: replace-with-rabbitmq-user
  rabbitmq-password: replace-with-rabbitmq-password
  grafana-admin-user: replace-with-grafana-admin
  grafana-admin-password: replace-with-grafana-password
